const Mongoose = require('mongoose')

const ModelSchema = new Mongoose.Schema({
    coordenada: Array,
    data: String,
    hora: String,
    cliente_id: String,
    cliente: Object,
    responsavel_id: String,
    responsavel: Object,
    hora_inicio: String,
    hora_encerramento: String,
    contato: String,
    status: { type: String, default: 'agendada'},
    endereco: String,
    modulos: String,
    marca: String,
    inversores: String,
    stringbox: String,
    mppts: String,
    telhado: String,
    arranjos: String,
    cabeamento: String,
    disjuntor: String,
    canaleta: String,
    eletroduto: String,
    haste_terra: String,
    inclinacao: String,
    localizacao: String,
    condutor: String,
    compras: String,
    saida: String,
    chegada: String,
    km_chegada_adtina: String,
    km_chegada_cliente: String,
    km_saida_adtina: String,
    km_saida_cliente: String,
    horario_saida_adtina: String,
    horario_saida_cliente: String,
    horario_chegada_adtina: String,
    horario_chegada_cliente: String,
    ajudantes: String,
    criadoEm: { type: Date, default: Date.now }
})

module.exports = new Mongoose.model('ordem', ModelSchema)
